/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.eztixapp;

import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class WelcomeFrame extends javax.swing.JFrame {

    static <T> String genericDisplayBalance(T element) {
        return "Rp " + element;
    }
    
    static String statusrn;
    private Payment pushCoupon;
    
    public WelcomeFrame(String username, Payment pushCoupon) {
        initComponents();
        this.username = username;
        money.setEditable(false);
        balanceFieldOrderPage.setEditable(false);
        notEnough.setVisible(false);
        enough.setVisible(false);
        scanDataTable(username);
        
        TopUp balance = new TopUp();
        money.setText(genericDisplayBalance(balance.getBalance(this.username) - fprice));
        balanceFieldOrderPage.setText("Balance : " + genericDisplayBalance(balance.getBalance(this.username) - fprice));
        
        Membership statusR = new Membership();
        GoldMember statusG = new GoldMember();
        SilverMember statusS = new SilverMember();
        
        if (countTransaction() > 10) {
            memberStatus.setText(statusG.getStatus());
            statusrn = statusG.getStatus();
        } else if (countTransaction() > 5) {
            memberStatus.setText(statusS.getStatus());
            statusrn = statusS.getStatus();
        } else {
            memberStatus.setText(statusR.getStatus());
            statusrn = statusR.getStatus();
        }
        
        this.pushCoupon = pushCoupon;
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NavBar = new javax.swing.JPanel();
        Headline1 = new javax.swing.JLabel();
        Headline2 = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        HistoryButton = new javax.swing.JButton();
        OrderButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        memberStatus = new javax.swing.JTextField();
        Tab = new javax.swing.JPanel();
        HomePage = new javax.swing.JPanel();
        HomePageTitle1 = new javax.swing.JLabel();
        HomePageTitle2 = new javax.swing.JLabel();
        TopMovieTitle = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        money = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        OrderPage = new javax.swing.JPanel();
        OrderTitle1 = new javax.swing.JLabel();
        OrderTitle2 = new javax.swing.JLabel();
        Display = new javax.swing.JPanel();
        Display1 = new javax.swing.JPanel();
        javax.swing.JButton PayButton = new javax.swing.JButton();
        LocationLabel = new javax.swing.JLabel();
        MovieNameLabel = new javax.swing.JLabel();
        SeatsLabel = new javax.swing.JLabel();
        LocationInput = new javax.swing.JComboBox<>();
        MovieNameInput = new javax.swing.JComboBox<>();
        SeatsInput = new javax.swing.JSpinner();
        TimeLabel = new javax.swing.JLabel();
        TimeInput = new javax.swing.JComboBox<>();
        Display2 = new javax.swing.JPanel();
        javax.swing.JButton BackButton = new javax.swing.JButton();
        javax.swing.JButton OrderFixButton = new javax.swing.JButton();
        SeatsPicturePanel = new javax.swing.JPanel();
        balanceFieldOrderPage = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        total = new javax.swing.JTextField();
        enough = new javax.swing.JLabel();
        notEnough = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        disc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        finalPrice = new javax.swing.JTextField();
        HistoryPage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoryTable = new javax.swing.JTable();
        HistoryTitle1 = new javax.swing.JLabel();
        HistoryTitle2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(582, 504));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setMinimumSize(new java.awt.Dimension(582, 504));

        NavBar.setBackground(new java.awt.Color(0, 144, 158));

        Headline1.setFont(new java.awt.Font("Plus Jakarta Sans",Font.BOLD, 24)); // NOI18N
        Headline1.setForeground(new java.awt.Color(255, 255, 255));
        Headline1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Headline1.setText("EZ-Tix");
        Headline1.setToolTipText("");

        Headline2.setFont(new java.awt.Font("Plus Jakarta Sans",Font.BOLD, 14)); // NOI18N
        Headline2.setForeground(new java.awt.Color(255, 255, 255));
        Headline2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Headline2.setText("---Tix---");
        Headline2.setToolTipText("");

        HomeButton.setBackground(new java.awt.Color(204, 204, 204));
        HomeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HomeButton.setText("Home");
        HomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeButtonMouseClicked(evt);
            }
        });
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        HistoryButton.setBackground(new java.awt.Color(204, 204, 204));
        HistoryButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HistoryButton.setText("History");
        HistoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoryButtonMouseClicked(evt);
            }
        });
        HistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryButtonActionPerformed(evt);
            }
        });

        OrderButton.setBackground(new java.awt.Color(204, 204, 204));
        OrderButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OrderButton.setText("Order");
        OrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderButtonMouseClicked(evt);
            }
        });
        OrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(0, 18, 83));
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        memberStatus.setEditable(false);
        memberStatus.setBackground(new java.awt.Color(255, 255, 255));
        memberStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        memberStatus.setForeground(new java.awt.Color(0, 18, 83));
        memberStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        memberStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavBarLayout = new javax.swing.GroupLayout(NavBar);
        NavBar.setLayout(NavBarLayout);
        NavBarLayout.setHorizontalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Headline1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Headline2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HistoryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OrderButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HomeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(NavBarLayout.createSequentialGroup()
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(NavBarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(memberStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NavBarLayout.setVerticalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(Headline1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Headline2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(memberStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(15, 15, 15))
        );

        Tab.setBackground(new java.awt.Color(0, 51, 51));
        Tab.setLayout(new java.awt.CardLayout());

        HomePage.setBackground(new java.awt.Color(0, 104, 132));

        HomePageTitle1.setFont(new java.awt.Font("Plus Jakarta Sans", Font.BOLD, 50)); // NOI18N
        HomePageTitle1.setText("EZ-Tix");
        HomePageTitle1.setToolTipText("");

        TopMovieTitle.setFont(new java.awt.Font("Plus Jakarta Sans", Font.BOLD, 12)); // NOI18N
        TopMovieTitle.setText("TOP MOVIE THIS WEEK!");

        jLabel7.setFont(new java.awt.Font("Plus Jakarta Sans", Font.PLAIN, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Avatar II: The Way of Water");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel8.setFont(new java.awt.Font("Plus Jakarta Sans", Font.PLAIN, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Thor : Love and Thunder");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel9.setFont(new java.awt.Font("Plus Jakarta Sans", Font.PLAIN, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Black Panther : Wakanda Forever");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        money.setBackground(new java.awt.Color(255, 158, 11));
        money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyActionPerformed(evt);
            }
        });

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 102));
        jButton3.setFont(new java.awt.Font("STZhongsong", 0, 12)); // NOI18N
        jButton3.setText("SEE DISCOUNT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HomePageLayout = new javax.swing.GroupLayout(HomePage);
        HomePage.setLayout(HomePageLayout);
        HomePageLayout.setHorizontalGroup(
            HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePageLayout.createSequentialGroup()
                        .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TopMovieTitle)
                            .addGroup(HomePageLayout.createSequentialGroup()
                                .addComponent(money, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HomePageTitle2)
                            .addComponent(HomePageTitle1))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePageLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
            .addGroup(HomePageLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        HomePageLayout.setVerticalGroup(
            HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HomePageTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(money, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(HomePageTitle2)
                .addGap(26, 26, 26)
                .addComponent(TopMovieTitle)
                .addGap(16, 16, 16)
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        Tab.add(HomePage, "card2");

        OrderPage.setBackground(new java.awt.Color(0, 104, 132));

        OrderTitle1.setFont(new java.awt.Font("STZhongsong", 1, 36)); // NOI18N
        OrderTitle1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        OrderTitle1.setText("Order");

        OrderTitle2.setFont(new java.awt.Font("STZhongsong", 0, 14)); // NOI18N
        OrderTitle2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        OrderTitle2.setText("Page");

        Display.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Display.setLayout(new java.awt.CardLayout());

        Display1.setBackground(new java.awt.Color(204, 204, 204));

        PayButton.setFont(new java.awt.Font("STZhongsong", 0, 12)); // NOI18N
        PayButton.setText("Pay");
        PayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PayButtonMouseClicked(evt);
            }
        });
        PayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayButtonActionPerformed(evt);
            }
        });

        LocationLabel.setFont(new java.awt.Font("STZhongsong", 2, 14)); // NOI18N
        LocationLabel.setText("Theater Location");

        MovieNameLabel.setFont(new java.awt.Font("STZhongsong", 2, 14)); // NOI18N
        MovieNameLabel.setText("Movie Name");

        SeatsLabel.setFont(new java.awt.Font("STZhongsong", 2, 14)); // NOI18N
        SeatsLabel.setText("Lots of Seats");

        LocationInput.setFont(new java.awt.Font("STZhongsong", 0, 12)); // NOI18N
        LocationInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jatos", "TSM", "Paris Van Java", "Paskal 23" }));

        MovieNameInput.setFont(new java.awt.Font("STZhongsong", 0, 12)); // NOI18N
        MovieNameInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avatar II : The Way Of Water", "Thor: Love and Thunder", "Black Panther: Wakanda Forever", "Tegar" }));

        TimeLabel.setFont(new java.awt.Font("STZhongsong", 2, 14)); // NOI18N
        TimeLabel.setText("Time");

        TimeInput.setFont(new java.awt.Font("STZhongsong", 0, 12)); // NOI18N
        TimeInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11:00 - 13:00", "13:00 - 15:00", "15:00 - 17:00", "17:00 - 19:00", "19:00 - 21:00", "21:00 - 23:00" }));

        javax.swing.GroupLayout Display1Layout = new javax.swing.GroupLayout(Display1);
        Display1.setLayout(Display1Layout);
        Display1Layout.setHorizontalGroup(
            Display1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Display1Layout.createSequentialGroup()
                .addGroup(Display1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Display1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Display1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(Display1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MovieNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LocationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SeatsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Display1Layout.createSequentialGroup()
                                .addGroup(Display1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LocationInput, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MovieNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SeatsInput, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TimeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 37, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        Display1Layout.setVerticalGroup(
            Display1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Display1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(LocationLabel)
                .addGap(5, 5, 5)
                .addComponent(LocationInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MovieNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MovieNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeatsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeatsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(PayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Display.add(Display1, "card2");

        Display2.setBackground(new java.awt.Color(204, 204, 204));

        BackButton.setFont(new java.awt.Font("STZhongsong", 0, 12)); // NOI18N
        BackButton.setText("Back");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });

        OrderFixButton.setFont(new java.awt.Font("STZhongsong", 0, 12)); // NOI18N
        OrderFixButton.setText("Order");
        OrderFixButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderFixButtonMouseClicked(evt);
            }
        });
        OrderFixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderFixButtonActionPerformed(evt);
            }
        });

        balanceFieldOrderPage.setBackground(new java.awt.Color(242, 242, 242));
        balanceFieldOrderPage.setFont(new java.awt.Font("STZhongsong", 0, 12)); // NOI18N
        balanceFieldOrderPage.setText("Balance : Rp ");

        jLabel1.setFont(new java.awt.Font("STZhongsong", 2, 18)); // NOI18N
        jLabel1.setText("Confirmation");

        jLabel3.setText("Your Total");

        jLabel4.setText("Your Balance");

        jLabel6.setText(":");

        jLabel10.setText(":");

        jLabel14.setFont(new java.awt.Font("STZhongsong", 2, 11)); // NOI18N
        jLabel14.setText("confirm your order by click the order button");

        jButton1.setText("Top Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        total.setEditable(false);

        enough.setForeground(new java.awt.Color(0, 255, 0));
        enough.setText("ENOUGH");

        notEnough.setForeground(new java.awt.Color(255, 0, 0));
        notEnough.setText("NOT ENOUGH");

        jLabel2.setText("Discount");

        jLabel5.setText(":");

        disc.setEditable(false);
        disc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discActionPerformed(evt);
            }
        });

        jLabel11.setText("Final Price");

        jLabel12.setText(":");

        finalPrice.setEditable(false);

        javax.swing.GroupLayout SeatsPicturePanelLayout = new javax.swing.GroupLayout(SeatsPicturePanel);
        SeatsPicturePanel.setLayout(SeatsPicturePanelLayout);
        SeatsPicturePanelLayout.setHorizontalGroup(
            SeatsPicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeatsPicturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SeatsPicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SeatsPicturePanelLayout.createSequentialGroup()
                        .addComponent(balanceFieldOrderPage, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel14)
                    .addGroup(SeatsPicturePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(SeatsPicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SeatsPicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel11))
                        .addGap(40, 40, 40)
                        .addGroup(SeatsPicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(SeatsPicturePanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(disc))
                            .addGroup(SeatsPicturePanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SeatsPicturePanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(enough)
                                .addGap(31, 31, 31)
                                .addComponent(notEnough)
                                .addGap(33, 33, 33))
                            .addGroup(SeatsPicturePanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(finalPrice)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        SeatsPicturePanelLayout.setVerticalGroup(
            SeatsPicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeatsPicturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SeatsPicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceFieldOrderPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SeatsPicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SeatsPicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(enough)
                    .addComponent(notEnough))
                .addGap(18, 18, 18)
                .addGroup(SeatsPicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(disc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SeatsPicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(finalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        javax.swing.GroupLayout Display2Layout = new javax.swing.GroupLayout(Display2);
        Display2.setLayout(Display2Layout);
        Display2Layout.setHorizontalGroup(
            Display2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Display2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Display2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeatsPicturePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Display2Layout.createSequentialGroup()
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                        .addComponent(OrderFixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Display2Layout.setVerticalGroup(
            Display2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Display2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SeatsPicturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(Display2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OrderFixButton, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Display.add(Display2, "card3");

        javax.swing.GroupLayout OrderPageLayout = new javax.swing.GroupLayout(OrderPage);
        OrderPage.setLayout(OrderPageLayout);
        OrderPageLayout.setHorizontalGroup(
            OrderPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OrderPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderPageLayout.createSequentialGroup()
                        .addComponent(Display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderPageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(OrderPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrderTitle1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OrderTitle2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
        );
        OrderPageLayout.setVerticalGroup(
            OrderPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPageLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(OrderTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrderTitle2)
                .addGap(18, 18, 18)
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Tab.add(OrderPage, "card3");

        HistoryPage.setBackground(new java.awt.Color(0, 104, 132));

        HistoryTable.setBackground(new java.awt.Color(204, 204, 204));
        HistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Location", "Movie Name", "Tickets", "Date & Time Order", "Total Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(HistoryTable);

        HistoryTitle1.setFont(new java.awt.Font("STZhongsong", 1, 36)); // NOI18N
        HistoryTitle1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        HistoryTitle1.setText("History");

        HistoryTitle2.setFont(new java.awt.Font("STZhongsong", 0, 14)); // NOI18N
        HistoryTitle2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        HistoryTitle2.setText("Order");

        javax.swing.GroupLayout HistoryPageLayout = new javax.swing.GroupLayout(HistoryPage);
        HistoryPage.setLayout(HistoryPageLayout);
        HistoryPageLayout.setHorizontalGroup(
            HistoryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistoryPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HistoryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HistoryTitle2)
                    .addComponent(HistoryTitle1))
                .addGap(25, 25, 25))
        );
        HistoryPageLayout.setVerticalGroup(
            HistoryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistoryPageLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(HistoryTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HistoryTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        Tab.add(HistoryPage, "card4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Tab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void HistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HistoryButtonActionPerformed

    private void OrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderButtonActionPerformed

    private void PayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayButtonActionPerformed

    private void HomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseClicked
        // TODO add your handling code here:
        // Remove Panel
        Tab.removeAll();
        Tab.repaint();
        Tab.revalidate();
        
        // Add Panel
        Tab.add(HomePage);
        Tab.repaint();
        Tab.revalidate();
    }//GEN-LAST:event_HomeButtonMouseClicked

    private void OrderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderButtonMouseClicked
        // TODO add your handling code here:
        // Remove Panel
        Tab.removeAll();
        Tab.repaint();
        Tab.revalidate();
        
        // Add Panel
        Tab.add(OrderPage);
        Tab.repaint();
        Tab.revalidate();
    }//GEN-LAST:event_OrderButtonMouseClicked

    private void HistoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryButtonMouseClicked
        // TODO add your handling code here:
        // Remove Panel
        Tab.removeAll();
        Tab.repaint();
        Tab.revalidate();
        
        // Add Panel
        Tab.add(HistoryPage);
        Tab.repaint();
        Tab.revalidate();
    }//GEN-LAST:event_HistoryButtonMouseClicked

    private void PayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayButtonMouseClicked
        // TODO add your handling code here:
        int check = (Integer) SeatsInput.getValue();
        
        if (check <= 0 || check > 9) {
            JOptionPane.showMessageDialog(this, "You can't input this much numbers of seats", "Try again", JOptionPane.ERROR_MESSAGE);
        } else {
            // Remove Panel
            Display.removeAll();
            Display.repaint();
            Display.revalidate();
            
            
            int seat = (int) SeatsInput.getValue();
            int totalPrice = 35000 * seat;
            total.setText(String.valueOf(totalPrice));
            TopUp checkEnough = new TopUp();
            
            if(checkEnough.getBalance(username) > totalPrice) {
                notEnough.setVisible(false);
                enough.setVisible(true);
            } else {
                enough.setVisible(false);
                notEnough.setVisible(true);
            }
            
            //DISCOUNT
            int d = pushCoupon.getPayment();
            disc.setText(Integer.toString(d));
            
            //FINAL PRICE
            fprice = totalPrice - d;
            finalPrice.setText(Integer.toString(fprice));
            
            // Add Panel
            Display.add(Display2);
            Display.repaint();
            Display.revalidate();
        }
    }//GEN-LAST:event_PayButtonMouseClicked

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        // TODO add your handling code here:
        Display.removeAll();
        Display.repaint();
        Display.revalidate();
        
        // Add Panel
        Display.add(Display1);
        Display.repaint();
        Display.revalidate();
    }//GEN-LAST:event_BackButtonMouseClicked

    private void OrderFixButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderFixButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderFixButtonMouseClicked

    private void OrderFixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderFixButtonActionPerformed
        // TODO add your handling code here:
        int seat = (int) SeatsInput.getValue();
        int totalPrice = 35000 * seat;
        
        TopUp check = new TopUp();
        if(check.getBalance(username) > totalPrice) {
            JOptionPane.showMessageDialog(null, "We have confirm your order!");

            String location = (String) LocationInput.getSelectedItem();
            String movie = (String) MovieNameInput.getSelectedItem();
            String seats = String.valueOf(SeatsInput.getValue());
            String time = (String) TimeInput.getSelectedItem();
            ArrayList<String> order = new ArrayList<>();

            addToTable(location, movie, seats);

            order.add(location);
            order.add(movie);
            order.add(seats);
            order.add(time);

            WriteData write = new WriteData();
            write.WriteData(username, order);
            
            WriteData min = new WriteData();
            min.WriteData(username, -fprice);
            
            this.setVisible(false);
            new WelcomeFrame(username, new Payment()).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Top Up First!");
        }
    }//GEN-LAST:event_OrderFixButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void moneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new TopUpFrame(username, pushCoupon).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new TopUpFrame(username, pushCoupon).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void memberStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberStatusActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new PopUpVoucher(username, statusrn, pushCoupon).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void discActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discActionPerformed

    private void addToTable (String location, String movie, String tickets) {
        DefaultTableModel model = (DefaultTableModel) HistoryTable.getModel();
        model.addRow(new Object[] {location, movie, tickets});
    }
    
    private boolean scanDataTable(String username) {
        try {
            File user = new File (username + ".txt");
            Scanner dataScanner = new Scanner(user);
            while (dataScanner.hasNextLine()) {
                String[] keyValue = dataScanner.nextLine().split("/");
                DefaultTableModel model = (DefaultTableModel) HistoryTable.getModel();
                model.addRow(new Object[] {keyValue[0], keyValue[1], keyValue[2]});
            }
            dataScanner.close();
        } catch (Exception e) {
            e.printStackTrace();
            return true;
        }
        return true;
    }
    
    private int countTransaction() {
        int count = 0;
        
        File user = new File (username + ".txt");
        Scanner dataScanner = null;
        try {
            dataScanner = new Scanner(user);
        } catch (FileNotFoundException ex) {
            return 0;
        }
        
        while (dataScanner.hasNextLine()) {
            count++;
            dataScanner.nextLine();
        }
        dataScanner.close();
        
        return count;
    }
    
    public int fprice = 0;
    private String username;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Display;
    private javax.swing.JPanel Display1;
    private javax.swing.JPanel Display2;
    private javax.swing.JLabel Headline1;
    private javax.swing.JLabel Headline2;
    private javax.swing.JButton HistoryButton;
    private javax.swing.JPanel HistoryPage;
    private javax.swing.JTable HistoryTable;
    private javax.swing.JLabel HistoryTitle1;
    private javax.swing.JLabel HistoryTitle2;
    private javax.swing.JButton HomeButton;
    private javax.swing.JPanel HomePage;
    private javax.swing.JLabel HomePageTitle1;
    private javax.swing.JLabel HomePageTitle2;
    private javax.swing.JComboBox<String> LocationInput;
    private javax.swing.JLabel LocationLabel;
    private javax.swing.JComboBox<String> MovieNameInput;
    private javax.swing.JLabel MovieNameLabel;
    private javax.swing.JPanel NavBar;
    private javax.swing.JButton OrderButton;
    private javax.swing.JPanel OrderPage;
    private javax.swing.JLabel OrderTitle1;
    private javax.swing.JLabel OrderTitle2;
    private javax.swing.JSpinner SeatsInput;
    private javax.swing.JLabel SeatsLabel;
    private javax.swing.JPanel SeatsPicturePanel;
    private javax.swing.JPanel Tab;
    private javax.swing.JComboBox<String> TimeInput;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JLabel TopMovieTitle;
    private javax.swing.JTextField balanceFieldOrderPage;
    private javax.swing.JTextField disc;
    private javax.swing.JLabel enough;
    private javax.swing.JTextField finalPrice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField memberStatus;
    private javax.swing.JTextField money;
    private javax.swing.JLabel notEnough;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
